apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: deploy-dash
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 3000
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1536Mi
  ingresses:
    - https://gh-deploy-dash.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 60
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
  envFrom:
    - secret: gh-deploy-dash
  env:
    - name: NODE_ENV
      value: PRODUCTION
